---

- name: Preparando ambiente
  hosts: localhost
  connection: local
  become: true
  tasks:

### Start google

- name: Instalar Google Chrome no Linux Mint
  hosts: all
  become: yes

  tasks:

    - name: Baixar o pacote .deb do Google Chrome
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
        mode: '0644'

    - name: Instalar o pacote .deb do Google Chrome
      ansible.builtin.apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
        state: present
        update_cache: yes

    - name: Remover arquivo .deb temporário
      ansible.builtin.file:
        path: /tmp/google-chrome-stable_current_amd64.deb
        state: absent

## End Google





    - name: Atualizando Pacotes

      apt:
        upgrade: full
        update_cache: yes

    - name: Instalando Softwares via APT
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
        update_cache: yes

      loop:

          - vim
          - htop
#          - unzip
          - curl
          - wget
          - tree
          - git
#          - gparted
          - python3-pip
          - terminator
          - google-chrome-stable


#    - name: Adicionando usuário 'jairo' ao grupo 'sudo'
#      user:
#        name: 'USER'
#        groups: sudo
#        append: yes

#    - name: Habilitando UFW na Inicialização
#      service:
#        name: ufw
#        enabled: yes


#    - name: Liberar acesso as portas do Firewall
#      community.general.ufw:
#        rule: allow
#        port: '{{ item }}'
#        src: 192.168.0.0/24
#        proto: tcp
#        state: enabled
#        log: yes
#      loop:
#          - '22'
#          - '3389'



    - name: Instalando Softwares via Snap
      snap:
        name: '{{ item }}'
        classic: yes

      loop:

        - remmina
        - notion-snap
        - telegram-desktop
        - discord
        - teams-insiders
        - vlc
        - spotify
