---
- name: Preparando ambiente
  hosts: localhost
  connection: local
  become: true
  tasks:
### Start google
- name: Instalar Google Chrome no Linux Mint
  hosts: all
  become: yes  # Executa as tarefas com privilégios de superusuário (sudo)

  tasks:
    - name: Baixar o pacote .deb do Google Chrome
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /home/jairo/google-chrome-stable_current_amd64.deb
        mode: '0644'

    - name: Instalar o pacote .deb do Google Chrome
      ansible.builtin.apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
        state: present
        update_cache: yes
      notify:
        - Remover arquivo .deb temporário

  handlers:
    - name: Remover arquivo .deb temporário
      ansible.builtin.file:
        path: /home/jairo/google-chrome-stable_current_amd64.deb
        state: absent
## End Google


    - name: Atualizando Pacotes
      apt:
        upgrade: full
        update_cache: yes

    - name: Instalando Softwares via APT
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
        update_cache: yes
      loop:
          - vim
          - htop
#          - unzip
          - curl
#          - bc
#          - wine
          - wget
          - tree
#          - make
          - git
#          - gparted
#          - apt-transport-https
#          - ca-certificates
#          - gnupg
          - python3-pip
#          - bash-completion
#          - gnupg-agent
          - terminator
#          - flameshot
#          - fonts-hack
#          - mlocate
          - bluetooth
          - bluez
          - bluez-tools
#          - rfkill
          - google-chrome-stable
#          - filezilla
#          - krita
          - ansible
          - ansible-lint
          - snapd
#          - gnome
#          - gnome-tweak-tool
#         - task-gnome-desktop
#         - xfce4
#         - xfce4-terminal
#         - xorg
#          - xserver-xorg-core
#          - xserver-xorg-input-all
#         - dbus-x11
#         - x11-xserver-utils
#          - ssl-cert 
          - ssh
#          - xrdp
#          - ufw
#          - fail2ban

#    - name: Configurando ambiente gráfico no usuário
#      ansible.builtin.copy:
#        src: xrdp/.xsession
#        dest: /home/USER/.xsession
#        owner: jairo
#        group: jairo
#        mode: '0755'

#    - name: Configurando ambiente gráfico padrão para todos os usuários
#      ansible.builtin.copy:
#        src: xrdp/.xsession
#        dest: /etc/skel/.xsession
#        owner: root
#        group: root
#        mode: '0644'

#    - name: Habilitando ambiente gráfico para todos usuários
#      ansible.builtin.replace:
#        path: /etc/X11/Xwrapper.config
#        regexp: 'allowed_users=console'
#        replace: 'allowed_users=anybody'

#    - name: Adicionando usuário 'xrdp' ao grupo 'ssl-cert'
#      user:
#        name: 'xrdp'
#        groups: 'ssl-cert'

#    - name: Adicionando usuário 'jairo' ao grupo 'sudo'
#      user:
#        name: 'USER'
#        groups: sudo
#        append: yes

#    - name: Habilitando SSH na Inicialização
#      service:
#        name: ssh
#        enabled: yes

#    - name: Habilitando XRDP na Inicialização
#      service:
#        name: xrdp
#        enabled: yes

#    - name: Habilitando UFW na Inicialização
#      service:
#        name: ufw
#        enabled: yes

#    - name: Liberar acesso as portas do Firewall
#      community.general.ufw:
#        rule: allow
#        port: '{{ item }}'
#        src: 192.168.0.0/24
#        proto: tcp
#        state: enabled
#        log: yes
#      loop:
#          - '22'
#          - '3389'

    - name: Instalando Softwares via Snap
      snap:
        name: '{{ item }}'
        classic: yes
      loop:
#        - core
#        - snap-store
#        - phpstorm
#        - code
#        - mysql-workbench-community
#        - robo3t-snap
#        - postman
#        - insomnia
#        - gitkraken
        - remmina
        - notion-snap
#        - evernote-web-client
#        - onlyoffice-desktopeditors
#        - brave
#        - opera
#        - slack
#        - telegram-desktop
        - discord
#        - teams-insiders
#        - zoom-client
#        - obs-studio
#        - audacity
#        - youtube-dl
        - vlc
        - spotify
#        - google-play-music-desktop-player
#        - plexmediaserver
#        - sc-controller
#        - retroarch
#        - supertux
#       - kbreakout
#      - antstream-arcade
